##
# -- IO Config --
#
#   - lid:LogSource_unix
#   - lid:LogSource_apache
#   - lid:LogSource_audit
#   - lid:LogSource_ftp
##

source: scenario/input/auth.log
sourceLogpai: scenario/input/auth.log_structured.csv
sourceLogpaiTemplate: scenario/input/auth.log_templates.csv

logFormat: unix
logSourceType: auth

isOverrideExisting: false
paramExtractAttempt: 3

targetOttr: scenario/output/auth.log_structured.ottr
targetOttrTurtle: scenario/output/auth.ttl

targetOttrBase: scenario/config-base.ottr
targetStanfordNer: scenario/config-ner.rules
targetConfigTurtle: scenario/config-turtle.ttl


